### ISSUE TITLE
#BUG#10月份生日身份证校验错误

### ISSUE THREAD

**Issue by xw-fu** [douyasi/identity-card#1]
`return preg_match('/^\d{6}(18|19|20)\d{2}(0[1-9]|1[12])(0[1-9]|[12]\d|3[01])\d{3}(\d|X)$/', $pid);`

此处正则有问题， 10月份生日校验不通过。

**Comment by ycrao** [comment]
@chrisfoon 感谢你的汇报，稍后我会在新版里做出修正
