### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by ProjectMoss** [douyasi/identity-card#10]
能转成一个CSV的字典文件吗，有很多时候都是在数据库匹配的。

**Comment by ycrao** [comment]
@ProjectMoss 本身就提供 [sqlite](https://github.com/douyasi/identity-card/blob/master/db/database.sqlite) 格式的数据库，可以使用数据库软件打开自行转换，再者也可以自行处理原始[爬虫数据](https://github.com/douyasi/identity-card/tree/master/crawler/data)。
