### ISSUE TITLE
我是非法地区 😂

### ISSUE THREAD

**Issue by karoc** [douyasi/identity-card#3]
话说，海南乐东的身份证前六位现在不知道是多少，但是我的是460033。
最新的行政区划是469027，[这里可看](http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html)
看程序里面的走向，是会走到非法地区啊😂

**Comment by ycrao** [comment]
本类库能够覆盖大部分校验，依赖于政府公开标准数据（GB/T 2260-2007），当然都过去这么久，行政区划都有所变更。

**Comment by ycrao** [comment]
@karoc 你所提供的并未形成国标，新行政区划代码的推行也不会意味着老身份证号（如你460033打头的）会失效过期，新老并存的情况仍然存在。有时间我会整理一下新旧数据差异，完成部分支持。
