### ISSUE TITLE
请问支持15位身份证号么？试过几个不行啊。

### ISSUE THREAD

**Issue by Nicolas-One** [douyasi/identity-card#7]
请问支持15位身份证号么？试过几个不行啊。

**Comment by ycrao** [comment]
不支持，中国大陆地区基本上都是使用18位了，除非某些过时的老系统。15位身份证号码升18位算法可参考这篇文章： https://blog.csdn.net/Hello_Strangers/article/details/72870567 。你可以自行升级为18位之后再调用本插件。
